[ i18n sprint ] Move translations from language specific lib-home-page templates to properties.
vivo-project/VIVO pull request #3780
Opened 2022-10-07 13:53 UTC by litvinovg

[Companion PR](https://github.com/vivo-project/VIVO-languages/pull/115)
#What does this pull request do?#
Moves translations from language specific lib-home-page templates to properties.
#How to test#
Open home page, view list of research types

2022-10-20 12:58 UTC, chenejac approved these changes

2022-11-04 12:59 UTC, bkampe approved these changes
Works like it should. 
Maybe the design/arrangement could be improved a little bit.

2022-11-07 07:13 UTC, litvinovg commented
> Works like it should. Maybe the design/arrangement could be improved a little bit.

I will try to prepare a solution with a better look

2022-11-07 14:35 UTC, bkampe approved these changes
Works and is looking good.

2022-11-08 10:56 UTC, chenejac requested changes

2022-11-08 10:56 UTC, chenejac commented on webapp/src/main/webapp/templates/freemarker/lib/lib-home-page.ftl
> +    </ul>
There is no opening tag for this?

2022-11-08 12:23 UTC, litvinovg commented on webapp/src/main/webapp/templates/freemarker/lib/lib-home-page.ftl
> +    </ul>
Removed closing tag. Thank you.

2022-11-08 12:38 UTC, chenejac approved these changes

2022-11-08 12:38 UTC, merged