[ i18n sprint ] from fr_CA lang files
vivo-project/VIVO pull request #3783
Opened 2022-10-14 16:03 UTC by litvinovg

[Companion PR](https://github.com/vivo-project/Vitro/pull/336)
[Companion PR](https://github.com/vivo-project/Vitro-languages/pull/63)

2022-10-20 13:15 UTC, chenejac requested changes

2022-10-20 13:15 UTC, chenejac commented on webapp/src/main/webapp/templates/freemarker/edit/forms/addRoleToPersonTwoStage.ftl
>                 		    ${htmlForElements["startField"]} ${yearHint}
This is producing (in adding head of or member of):
Start Year Year 

The word year is two times. The same is for end_year (after adding end_year in the property file)

2022-10-20 13:15 UTC, chenejac commented on webapp/src/main/webapp/templates/freemarker/edit/forms/addRoleToPersonTwoStage.ftl
>                 		    ${htmlForElements["startField"]} ${yearHint}
also, a place holder for Organization name has some duplicated text in adding role -  a member of.
Select an existing Select a type or create a new one

2022-10-20 13:15 UTC, chenejac commented on webapp/src/main/webapp/templates/freemarker/edit/forms/addRoleToPersonTwoStage.ftl
>                 		    ${htmlForElements["startField"]} ${yearHint}
For Creation of advisor relationship, in the placeholder Advisee and Subject Field are not internationalized

2022-10-21 09:43 UTC, chenejac approved these changes
Thanks

2022-11-06 14:18 UTC, VeljkoMaksimovic approved these changes

2022-11-07 16:10 UTC, VeljkoMaksimovic approved these changes

2022-11-08 09:42 UTC, chenejac approved these changes

2022-11-15 09:06 UTC, merged