[i18n-3762] Moving UI labels translations into vivo
vivo-project/VIVO pull request #3798
Opened 2022-11-23 10:19 UTC by chenejac

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3762](https://github.com/vivo-project/VIVO/issues/3762)

[Companion PR](https://github.com/vivo-project/Vitro/pull/350)

# What does this pull request do?
Moving UI labels translations from VIVO-languages into VIVO (+ adoption of a pom file)

# What's new?
webapp directories from VIVO-languages repository are not needed any more. Together with [PR](https://github.com/vivo-project/VIVO/pull/3797) for doing the same for home directories from Vitro-languages should enable archiving the VIVO-languages repositories.

# How should this be tested?

- Checkout https://github.com/vivo-project/VIVO-languages/tree/i18n-redesign as VIVO-languages project
- Remove VIVO home and install the new, fresh instance of VIVO
- Validate it is working as expected
- Try switching between all 8 languages (set in the runtime.properties languages.selectableLocales = en_US, de_DE, sr_Latn_RS, ru_RU, fr_CA, en_CA, es, pt_BR)
- 

# Interested parties
Tag (@ mention) interested parties or, if unsure, @VIVO-project/vivo-committers

2022-11-28 14:54 UTC, litvinovg commented
It looks like there are some differences with current data in VIVO.
Report
[reportVIVO.txt](https://github.com/vivo-project/Vitro/files/10104777/reportVIVO.txt)

2022-11-28 15:50 UTC, litvinovg commented
[report3.txt](https://github.com/vivo-project/VIVO/files/10105292/report3.txt)

2022-11-29 11:54 UTC, michel-heon commented
@litvinovg and @chenejac 
A new generation of ontologies is available at

 [(https://github.com/michel-heon/vivo-i18n-onto-lang)](https://github.com/michel-heon/vivo-i18n-onto-lang)

### Details about directories
- Data : contains the transformation transient files
-- Note: data/ontologies_ttl/ contains for each key the ontological correspondence in all languages.
- script: contains the transformation programs 
- target: contains the result of the distrubuted transformation according to the structure of the Vitro, Vitro-languages and VIVO-languages folders

2022-11-29 14:14 UTC, litvinovg commented
[vivo-report-29.11.2022-1.txt](https://github.com/vivo-project/VIVO/files/10113806/vivo-report-29.11.2022-1.txt)

2022-11-29 14:18 UTC, litvinovg commented on installer/example-settings.xml
> +                <vivo-dir>d:/Projekti/VIVO/home</vivo-dir>
I think changes in this file should be reverted.

2022-11-29 14:23 UTC, litvinovg requested changes
Please remove local settting from example-settings.xml

2022-11-29 15:35 UTC, litvinovg approved these changes

2022-12-05 10:49 UTC, michel-heon commented
For @chenejac and @litvinovg 
### INSTALLATION ACTIONS;
- git clone VIVO, Vitro, VIVO-languages, Vitro-languages
- checkout i18-redesign for each repo
- Config settings.xml. applicationSetup.n3, runtime.properties
- setting runtime.properties  : 
        RDFService.languageFilter = true
        languages.selectableLocales = en_US, de_DE, sr_Latn_RS, ru_RU, fr_CA, en_CA, es, pt_BR
- clean .m2 (rm -rf ~/.m2/*)
- start vivo installation (cd $VIVO; mvn clean install -s installer/settings.xml 
- copy sample sample-data-i18n.ttl sample-data-i18n-de_DE.ttl sample-data-i18n-en_CA.ttl sample-data-i18n-en_US.ttl sample-data-i18n-fr_CA.ttl sample-data-i18n-fr_FR.ttl in $HOME/vivo/home/rdf/abox/filegraph
- Start VIVO
### FIRST TESTING adn RESULTS:
- Check the home page for each language (Result OK)
- Capability map: Does not work for data not implemented in the target language 
- For a person ( ex.: Pierce, Franklin J ) the titles (professor) are translated only for English and French
- Menu title - changes appropriately for all languages
- Physics Department ( The title - The Physics Department is in the College of Science of Sample University - still remains in English)
- for the event "17th Annual Conference on Philosophy and Rhetoric" (the default language of the title is German for all non-implemented languages, when it should be English)
- Validate test page: (Works correctly for all languages)
- Physics Department ( The title - The Physics Department is in the College of Science of Sample University - always remains in English) regardless of the language context
- for the event "17th Annual Conference on Philosophy and Rhetoric" (the default language of the title is German for all non-implemented languages, when it should be English)

### SECOND TESTING
delete property files from  tomcat/webapp/vivo/*/i18n/*.properties to ensure that vivo is independent of the content of the property files

### ACTIONS:
- stop tomcat
- delete all language property files in tomcat/webapp/vivo/*/i18n/*.properties
- delete VIVO_HOME/{tdbContentModels, tdbModel, upgrade, uploads}
- start tomcat
### RESULTS:
Displaying the error message in VIVO
-----

> Fatal error
> 
> /vivo detected a fatal error during startup.
> 
>     FATAL: ConfigurationPropertiesSmokeTests
>         The application found no files in '/home/ubuntu/VIVO_LYRAIS_DEV/00-GIT/deploy/tomcat/webapps/vivo/i18n' .
>         edu.cornell.mannlib.vitro.webapp.config.ConfigurationPropertiesSmokeTests

-----

### SECOND TESTING-B OPTION
Deleting values in property files by:
`find . -name '*.properties' -path  '*/i18n/*' -exec bash -c 'echo "" >"$1"' _ {} \;`

### ACTION

	- Vivo works with the same observations as the  FIRST-TESTING

### CONCLUSTION
- In the tomcat log trace, it appears that vivo loads the language context from the ontology and property files. I suggest that the property file should be loaded only in case the ontology file does not exist. In addition to avoiding confusion, this would speed up the loading of VIVO
- The ConfigurationPropertiesSmokeTests smoktest should pass on the condition that one of the two files (ontology or properties) exists.
- the sample project ( https://github.com/vivo-project/sample-data ) should be enhanced for each of the languages implemented in the VIVO core
- Check the behavior of Capability Map

2022-12-05 12:41 UTC, michel-heon commented
For @chenejac and @litvinovg 
## TESTING **COMMENT**
### INSTALLATION ACTIONS;
- git clone VIVO, Vitro and checkout PR"s for each repo
	git clone git@github.com:vivo-project/VIVO.git
	gh pr checkout 3798
	git clone git@github.com:vivo-project/Vitro.git
	gh pr checkout 350
- Config settings.xml. applicationSetup.n3, runtime.properties
- setting runtime.properties  : 
        RDFService.languageFilter = true
        languages.selectableLocales = en_US, de_DE, sr_Latn_RS, ru_RU, fr_CA, en_CA, es, pt_BR
- clean .m2 (rm -rf ~/.m2/*)
- start vivo installation (cd $VIVO; mvn clean install -s installer/settings.xml 
- copy sample sample-data-i18n.ttl sample-data-i18n-de_DE.ttl sample-data-i18n-en_CA.ttl sample-data-i18n-en_US.ttl sample-data-i18n-fr_CA.ttl sample-data-i18n-fr_FR.ttl in $HOME/vivo/home/rdf/abox/filegraph
- Start VIVO
### FIRST TESTING (read only mode) and RESULTS:
- Check the home page for each language (Result OK)
- Capability map: Does not work for data not implemented in the target language 
- For a person ( ex.: Peters, Jasper I  ) the title (Professor and Associate Dean) only in english and position values translate only for (English, French, German) and German is defalut value (English must be)
- Menu title - changes appropriately for all languages
- Physics Department ( The title - The Physics Department is in the College of Science of Sample University - still remains in English - must be accept translation)
- for the event "17th Annual Conference on Philosophy and Rhetoric" (the default language of the title is German for all non-implemented languages, when it should be English)
- the file tomcat/webapps/vivo/themes/nemo/i18n/all.properties is installed 

### SECOND TESTING (Edition mode and RESULTS):
- For organization: Physical (http://localhost:8080/vivo_i18n/individual/n1927) the preview value is not translated
- I added an organization with a summary in English, French and German and it works well
- I added a book and a publisher with labels in French and English and associated with a person (the language change works well for all additions)
### CONCLUSTION
- the sample project ( https://github.com/vivo-project/sample-data ) should be enhanced for each of the languages implemented in the VIVO core
- Check the behavior of Capability Map
- Pay attention to the default language (German instead of English)
- Several titles are not translated (position of persons/title of organizations, etc)
- In the runtime.properties file, I suggest to add a languages.default= property to allow setting the default language.

2022-12-05 12:43 UTC, michel-heon commented
For @chenejac and @litvinovg 
## TESTING **COMMENT**
### INSTALLATION ACTIONS;
- git clone VIVO, Vitro and checkout PR"s for each repo
	git clone git@github.com:vivo-project/VIVO.git
	gh pr checkout 3798
	git clone git@github.com:vivo-project/Vitro.git
	gh pr checkout 350
- Config settings.xml. applicationSetup.n3, runtime.properties
- setting runtime.properties  : 
        RDFService.languageFilter = true
        languages.selectableLocales = en_US, de_DE, sr_Latn_RS, ru_RU, fr_CA, en_CA, es, pt_BR
- clean .m2 (rm -rf ~/.m2/*)
- start vivo installation (cd $VIVO; mvn clean install -s installer/settings.xml 
- copy sample sample-data-i18n.ttl sample-data-i18n-de_DE.ttl sample-data-i18n-en_CA.ttl sample-data-i18n-en_US.ttl sample-data-i18n-fr_CA.ttl sample-data-i18n-fr_FR.ttl in $HOME/vivo/home/rdf/abox/filegraph
- Start VIVO
### FIRST TESTING (read only mode) and RESULTS:
- Check the home page for each language (Result OK)
- Capability map: Does not work for data not implemented in the target language 
- For a person ( ex.: Peters, Jasper I  ) the title (Professor and Associate Dean) only in english and position values translate only for (English, French, German) and German is defalut value (English must be)
- Menu title - changes appropriately for all languages
- Physics Department ( The title - The Physics Department is in the College of Science of Sample University - still remains in English - must be accept translation)
- for the event "17th Annual Conference on Philosophy and Rhetoric" (the default language of the title is German for all non-implemented languages, when it should be English)
- the file tomcat/webapps/vivo/themes/nemo/i18n/all.properties is installed 

### SECOND TESTING (Edition mode and RESULTS):
- For organization: Physical (http://localhost:8080/vivo_i18n/individual/n1927) the preview value is not translated
- I added an organization with a summary in English, French and German and it works well
- I added a book and a publisher with labels in French and English and associated with a person (the language change works well for all additions)
### CONCLUSTION
- the sample project ( https://github.com/vivo-project/sample-data ) should be enhanced for each of the languages implemented in the VIVO core
- Check the behavior of Capability Map
- Pay attention to the default language (German instead of English)
- Several titles are not translated (position of persons/title of organizations, etc)
- In the runtime.properties file, I suggest to add a languages.default= property to allow setting the default language.

2022-12-05 16:39 UTC, michel-heon commented
## Test on version 1.13.0 to validate that new problems are not caused by this PR
### Case 1:

> For a person ( ex.: Peters, Jasper I ) the title (Professor and Associate Dean) only in english and position values translate only for (English, French, German) and German is defalut value (English must be)

#### Result:

The problem exists before this PR

![image](https://user-images.githubusercontent.com/71774817/205687916-eab15eb8-67e5-43dd-b278-e22229900bf7.png)
---
### Case 2

> Physics Department ( The title - The Physics Department is in the College of Science of Sample University - still remains in English - must be accept translation)

#### Result:

The problem exists before this PR

![image](https://user-images.githubusercontent.com/71774817/205691972-4dd2330d-3269-4dde-afbb-76a0dee9b006.png)
---
### Case 3

for the event "17th Annual Conference on Philosophy and Rhetoric" (the default language of the title is German for all non-implemented languages, when it should be English)

### Result:

The problem exists before this PR

![image](https://user-images.githubusercontent.com/71774817/205691170-bece4e9a-d10a-406e-b149-cea901e9d2ee.png)

---
## Conclusion
All the problems existed before this PR

2022-12-06 08:40 UTC, michel-heon approved these changes

2022-12-06 10:16 UTC, merged