Enable war deployment model (#197.1)
vivo-project/VIVO pull request #3839
Opened 2023-02-23 20:20 UTC by wwelling

**Thank you for submitting a pull request! Title this pull request with a brief description of what the pull request fixes/improves/changes. Please describe the pull request in detail using the template below.**
* * *

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: (please link to issue)

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)

# What does this pull request do?
A brief description of what the intended result of the PR will be and/or what problem it solves.

# What's new?
An in-depth description of the changes made by this PR. Technical details and possible side effects. Include screenshots if appropriate.

Example:
* Changes x feature to such that y
* Added x
* Removed y

# How should this be tested?
A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the pull request does what is intended.

# Additional Notes:
Any additional information that you think would be helpful when reviewing this PR.

Example:
* Does this change require documentation to be updated? 
* Does this change add any new dependencies? 
* Does this change require any other modifications to be made to the repository? 
* Could this change impact execution of existing code?
* Large pull requests should be avoided. If this PR is large (more than 1,000 lines of codes), please provide short explanation why your contribution can't be decoupled in smaller PRs. 

# Interested parties
Tag (@ mention) interested parties or, if unsure, @VIVO-project/vivo-committers

2023-03-01 12:49 UTC, chenejac submitted a review, later dismissed
@wwelling it works for me. Please, double check two my comments.

2023-03-01 14:08 UTC, wwelling commented on installer/pom.xml
> +            <url>https://raw.github.com/vivo-project/dependencies/master/</url>
Updated.

2023-03-01 14:14 UTC, wwelling commented on installer/webapp/src/main/webResources/WEB-INF/classes/log4j.properties
> +log4j.appender.AllAppender.File= ${catalina.base}/logs/vivo.all.log
Trying this now.

2023-03-01 14:18 UTC, wwelling commented on installer/webapp/src/main/webResources/WEB-INF/classes/log4j.properties
> +log4j.appender.AllAppender.File= ${catalina.base}/logs/vivo.all.log
This works using the `app-name` variable.

2023-03-02 14:31 UTC, kaladay requested changes
The runtime properties has some commented out code still using `/usr/local`.

See:
```
home/src/main/resources/config/default.runtime.properties:176:#OpenSocial.tokenKeyFile = /usr/local/vivo/data/shindig/openssl/securitytokenkey.txt
home/src/main/resources/config/default.runtime.properties:361:# harvester.location = /usr/local/vivo/harvester/
```

I think these should be updated to `/opt/vivo` paths.

2023-03-02 14:39 UTC, wwelling commented
@kaladay these are changing back with the following PR. https://github.com/vivo-project/VIVO/pull/3844 Perhaps the following PR should be reviewed in replacement of this.

2023-03-06 13:39 UTC, chenejac commented
superseded by https://github.com/vivo-project/VIVO/pull/3844

2023-03-06 13:39 UTC, closed without merging