Codestyle
vivo-project/VIVO pull request #3840
Opened 2023-02-24 12:59 UTC by chenejac

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3814](https://github.com/vivo-project/VIVO/issues/3814)

[Linked Vitro PR](https://github.com/vivo-project/Vitro/pull/372)

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
https://wiki.lyrasis.org/display/VIVO/Code+Style+Guide

# What does this pull request do?
Adding code style into the VIVO/Vitro project

# What's new?
checkstyle.xml added into the Vitro root
checkstyle-suppression.xml added in the Vitro root (empty at the moment)
A wiki page added - https://wiki.lyrasis.org/display/VIVO/Code+Style+Guide
checkstyle.xml file linked in pom.xml file (at the moment configured to be skipped)

# How should this be tested?
Just for reviewing purposes there is commit with code formatted by using this code style at https://github.com/chenejac/VIVO/commit/863801995c1bcc9ed6685047d17db1c3e88f16e1
 Note: that is just for reviewing codestyle rules, alignment of code with rules will be run again after Feb 2023 sprint

# Interested parties
Tag (@ mention) interested parties or, if unsure, @VIVO-project/vivo-committers

2023-02-28 10:02 UTC, chenejac commented
> Should VIVO have its own checkstyles? Using Vitro from a sibling directory is not desirable.

I suppose there is no any sense in making different style rules for Vitro and VIVO, but we might also copy the same checkstyle.xml from Vitro to VIVO.  @wwelling the practice that Vitro and VIVO projects have to be in sibling directories will be changed in your PRs for improving build process?

2023-02-28 14:08 UTC, wwelling commented
@chenejac no that does not change. However, we should try, if possible, to not further the coupling.

2023-03-01 07:52 UTC, chenejac commented
> Isn't it possible to build VIVO without Vitro as a sibling directory as long as you do not require any custom changes or specific unpublished Vitro artifact?

Yes, you are right. I have copied checkstyle.xml and checkstyle-suppressions.xml to root of the VIVO project and fixed links in pom.xml file.

2023-03-01 14:43 UTC, wwelling submitted a review, later dismissed

2023-03-07 13:51 UTC, wwelling submitted a review, later dismissed
Ignoring comment cleanup as missed last review. ;)

2023-03-07 15:30 UTC, litvinovg approved these changes

2023-06-28 08:22 UTC, litvinovg requested changes
Let's increase character limit to 120as we discussed in committers call some time ago.

2023-06-28 08:22 UTC, litvinovg commented on checkstyle.xml
> +  4. Maximum line length is 100 characters (except for long URLs, packages or imports)
```suggestion
  4. Maximum line length is 120 characters (except for long URLs, packages or imports)
```

2023-06-28 08:22 UTC, litvinovg commented on checkstyle.xml
> +    <!-- Maximum line length is 100 characters -->
```suggestion
    <!-- Maximum line length is 120 characters -->
```

2023-06-28 08:22 UTC, litvinovg commented on checkstyle.xml
> +        <property name="max" value="100"/>
```suggestion
        <property name="max" value="120"/>
```

2023-06-28 09:31 UTC, litvinovg submitted a review, later dismissed

2023-09-14 11:34 UTC, litvinovg approved these changes

2023-09-14 11:34 UTC, merged