Added configuration example for feature toggle.
vivo-project/VIVO pull request #3916
Opened 2023-11-07 12:38 UTC by ivanmrsulja

# What does this pull request do?
Added configuration example of forgotPassword functionality feature toggle.

# What's new?
Added example of configuration in example.runtime.properties file.

# How should this be tested?
this should be tested together with the corresponding [Vitro PR](https://github.com/vivo-project/Vitro/pull/421).

# Interested parties
@chenejac @brianjlowe @litvinovg

2023-11-07 13:55 UTC, chenejac approved these changes
@ivanmrsulja thanks

2024-01-15 12:09 UTC, chenejac requested changes

2024-01-15 12:09 UTC, chenejac commented on home/src/main/resources/config/example.runtime.properties
> +authentication.forgotPassword = enabled
```suggestion
authentication.forgotPassword = enabled
authentication.forgotPassword.notify-admin = true
```

2024-01-19 09:39 UTC, litvinovg commented
@ivanmrsulja please resolve merge conflict

2024-02-12 09:13 UTC, chenejac requested changes

2024-02-12 09:13 UTC, chenejac commented on home/src/main/resources/config/example.runtime.properties
> +authentication.forgotPassword = false
```suggestion
authentication.forgotPassword = disabled
```

2024-03-07 18:10 UTC, wwelling commented on home/src/main/resources/config/example.runtime.properties
> +# Feature toggle for forgot password functionality
We probably want to provide the available options here. I assume `[enabled, disabled]`.

2024-04-28 15:26 UTC, chenejac approved these changes

2024-05-02 14:08 UTC, wwelling approved these changes

2024-05-02 14:43 UTC, litvinovg approved these changes

2024-05-10 09:32 UTC, merged