Translations for search related individuals
vivo-project/VIVO pull request #3928
Opened 2023-12-15 17:55 UTC by litvinovg

[Related Vitro PR](https://github.com/vivo-project/Vitro/pull/431)

# What does this pull request do?
Translations for VIVO individuals presented on search results page

@chenejac Added translations for different languages. We need reviews from native speakers.

2023-12-19 10:02 UTC, ivanmrsulja requested changes

2024-01-15 12:03 UTC, chenejac requested changes
@litvinovg the search query (created at the home page) is lost if locale is changed. I am wondering whether you can switch http method of the form to be GET instead of POST at the home page? I mean something similar as you already did for Vitro [here](https://github.com/vivo-project/Vitro/pull/382/files#diff-d61c7d638a762d87325baba90af65244adf6974987308ebfbc57a7ba7d014a86L37)? It should be also applied for VIVO themes (I suggest to do that for all three themes):

- https://github.com/vivo-project/VIVO/blob/75a1df02cb30b4c3d7cf2c571ee9b925fce213b1/webapp/src/main/webapp/themes/wilma/templates/page-home.ftl#L47
- https://github.com/vivo-project/VIVO/blob/75a1df02cb30b4c3d7cf2c571ee9b925fce213b1/webapp/src/main/webapp/themes/tenderfoot/templates/page/page-home.ftl#L43
- https://github.com/vivo-project/VIVO/blob/75a1df02cb30b4c3d7cf2c571ee9b925fce213b1/webapp/src/main/webapp/themes/nemo/templates/page-home.ftl#L43

2024-01-15 15:56 UTC, litvinovg commented
> @litvinovg the search query (created at the home page) is lost if locale is changed. I am wondering whether you can switch http method of the form to be GET instead of POST at the home page? I mean something similar as you already did for Vitro [here](https://github.com/vivo-project/Vitro/pull/382/files#diff-d61c7d638a762d87325baba90af65244adf6974987308ebfbc57a7ba7d014a86L37)? It should be also applied for VIVO themes (I suggest to do that for all three themes):
> 
>     * https://github.com/vivo-project/VIVO/blob/75a1df02cb30b4c3d7cf2c571ee9b925fce213b1/webapp/src/main/webapp/themes/wilma/templates/page-home.ftl#L47
> 
>     * https://github.com/vivo-project/VIVO/blob/75a1df02cb30b4c3d7cf2c571ee9b925fce213b1/webapp/src/main/webapp/themes/tenderfoot/templates/page/page-home.ftl#L43
> 
>     * https://github.com/vivo-project/VIVO/blob/75a1df02cb30b4c3d7cf2c571ee9b925fce213b1/webapp/src/main/webapp/themes/nemo/templates/page-home.ftl#L43

Done

2024-01-16 08:05 UTC, chenejac approved these changes
Well done

2024-01-23 09:27 UTC, milospp approved these changes

2024-02-13 09:12 UTC, merged