Disallow forms (with CAPTCHA) to bots
vivo-project/VIVO pull request #3936
Opened 2024-01-18 09:04 UTC by chenejac

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3935](https://github.com/vivo-project/VIVO/issues/3935)

# What does this pull request do?
Disallow access to /contact and /forgot-password to bots (at least to bots which respect robots.txt)

# What's new?
robots.txt is updated

# How should this be tested?
Run VIVO and try to access to /contact and /forgot-password from the web browser (this should work), and from an http client with specified user-agent to some of the popular [crawlers](https://deviceatlas.com/blog/most-active-crawlers-list)

# Interested parties
Tag (@ mention) interested parties or, if unsure, @VIVO-project/vivo-committers

2024-01-19 14:17 UTC, wwelling submitted a review, later dismissed
https://github.com/search?q=repo%3Avivo-project%2FVitro%20%2Fcontact&type=code

https://github.com/search?q=repo%3Avivo-project%2FVitro+%2FsubmitFeedback+&type=code

https://github.com/vivo-project/Vitro/pull/421/files#diff-a461e0c1d25d9f1433d95156cd7e1b2a79f90d138b2d46c95889567c2fb742d7R39

2024-01-22 08:55 UTC, ivanmrsulja approved these changes
Works as intended. But keep in mind that the instructions in robots.txt files cannot enforce crawler behavior to the site, just suggest it :smile: to stop crawlers from accessing the pages we can try to manually whitelist user agents on the backend but I think it is not needed.

2024-01-23 09:36 UTC, milospp approved these changes

2024-01-23 09:40 UTC, milospp commented
> Works as intended. But keep in mind that the instructions in robots.txt files cannot enforce crawler behavior to the site, just suggest it 😄 to stop crawlers from accessing the pages we can try to manually whitelist user agents on the backend but I think it is not needed.

I don't think we should manually detect robots and disable those pages, because we cannot be 100% sure who is robot and who is not just by header. That's why we have captcha on those pages.

2024-05-31 12:30 UTC, ivanmrsulja requested changes
One change requested as in: https://github.com/vivo-project/Vitro/pull/438#pullrequestreview-2090715175

2024-06-03 07:21 UTC, ivanmrsulja approved these changes
I have re-run all the tests using [Merkle](https://technicalseo.com/tools/robots-txt/) and now everything works as intended. Steps to reproduce the tests:
- Setup a publicly available VIVO server (I reccommend using a tool like [NGROK](https://ngrok.com/))
- If the vivo does not run on the root URL and instead you have to go to `/vivo` or something similar, you have to provide `robots.txt` manually in the text editor
- Choose the crawler of your choice from dropdown menu and try to fetch any of the disallowed domains

2024-06-06 14:42 UTC, balmas approved these changes
This works as advertised.  Tested with Merkle and confirmed that submitFeedback, contact and forgotPassword are all disallowed.

2024-06-13 14:16 UTC, wwelling approved these changes

2024-06-14 09:23 UTC, merged