Fix for VIVO-3949
vivo-project/VIVO pull request #3962
Opened 2024-03-25 14:34 UTC by litvinovg

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3949)**: (please link to issue)

# What does this pull request do?
Fixes authorization checks on website forms by providing information about faux property

# How should this be tested?
* Reproduce the problem in the issue
* Check that users with admin role are allowed to add and edit webpage faux object property with domain Person
* Try to add/create webpage as admin user
* Remove edit permission in faux object property configuration
* Try edit website, should not be authorized
* Remove add permission in faux object property configuration
* Try add website, should not be authorized

# Interested parties
@VIVO-project/vivo-committers

2024-04-15 09:03 UTC, chenejac requested changes
@litvinovg thanks for this. 

I have tested the PR and if I follow the PR instructions for testing everything is passing, but I noticed the following:

- I can't specify that admin is not authorized to remove website
- When edit is allowed, edit form is missing information about website type (this might be part of the another PR).

2024-04-28 15:24 UTC, chenejac approved these changes
@litvinovg thanks for this PR. We discussed at a committers' meeting that permissions for removing webpage will be part of the another PR. Therefore, this PR might be merged from my point of view.

2024-06-05 15:21 UTC, balmas commented
I have confirmed that following the instructions in the PR it works as advertised and note the same as @chenejac that having Add permission also grants Drop permission, even if that permission is removed.  I also note that it's not possible to have Edit but not Add.  I am not sure there's a scenario where one would want to allow someone to edit their website URL but not add another one, but it is a little inconsistent.

2024-06-13 14:31 UTC, wwelling approved these changes

2024-06-13 14:31 UTC, merged