Added permissions required to upload images
vivo-project/VIVO pull request #3988
Opened 2024-05-29 06:57 UTC by litvinovg

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3987)**

[VIVO PR](https://github.com/vivo-project/Vitro/pull/468)

# What does this pull request do?
Added permissions required to upload main images.

# How should this be tested?
* Reproduce the issue
* Test that users with following roles able to upload/remove images: Admin, Curator, Editor, Self editor

# Interested parties
@VIVO-project/vivo-committers

# Reviewers' expertise

Candidates for reviewing this PR should have some of the following expertises:
1. Access control

# Reviewers' report template
## General comment
A reviewer should provide here comments and suggestions for requested changes if any.
## Testing
A reviewer should briefly describe here how it was tested
## Code reviewing
A reviewer should briefly describe here which part was code reviewed

2024-05-29 18:14 UTC, balmas approved these changes
I can verify that this works. I tested for all role types (admin, curator, editor, self-editor) and confirm that before loading the new property files only the root user was able to add/edit/delete the profile image and after loading the new property files each role type had the ability to add/edit/delete the profileImage (where appropriate for that role/profile combination). Tested mainly in wilma theme but did a quick test with the self-editor role type in the other themes as well).

It would be ideal if there were an integration test to validate that all of the properties needed to support the default functionality of the webapp are there. It looks like the Selenium tests haven't been updated/used in years.  Not sure if there is another approach that would be easy to implement.

2024-05-29 19:26 UTC, gneissone commented
I built with the changes to VIVO and Vitro but still cannot see the image when logged out. @balmas were you also able to view the images when completely logged out and after doing a hard refresh on the page? Or in incognito/private mode?

2024-05-29 19:33 UTC, balmas commented
Oh, that's a good catch. I didn't try to do a hard refresh after logout. You are correct, they are not visible in that case.

2024-05-29 19:35 UTC, balmas requested changes
- Changing Review status to Request changes, as noted by @gneissone  the uploaded images aren't visible to public users

2024-05-30 06:39 UTC, litvinovg commented
Thanks for catching that! I updated permission sets. Please test one more time.

2024-05-31 11:46 UTC, balmas approved these changes
Retested and confirm that can now view the profile images as a public (non-logged in user), and image editing capabilities remain correct for all other user role types.

2024-06-03 17:52 UTC, gneissone approved these changes
Tested and appears to work as expected now, thanks!

2024-06-04 11:42 UTC, merged