Browse filter results on page
vivo-project/VIVO pull request #4005
Opened 2024-09-16 12:36 UTC by litvinovg

[Vitro PR](https://github.com/vivo-project/Vitro/pull/473)

# What does this pull request do?
Adds an option to select search filter to display filtered results on custom page.

# What's new?
Please take a look at Vitro PR first.
Updated PageManagement entry form files to align with Vitro PR.

# How should this be tested?
A description of what steps someone could take to:
* Create a new page in PageManagement menu. use type filter as an example
* Browse page, try selecting facets, alphabetical index, pagination
* Test the same in non i18n VIVO
 
# Additional Notes:
This change require documentation to be updated.

# Interested parties
@hauschke @VIVO-project/vivo-committers

# Reviewers' expertise

Candidates for reviewing this PR should have some of the following expertises:
1. Java
2. Freemarker

# Reviewers' report template
**Please update the following template which should be used by reviewers.**
## General comment
A reviewer should provide here comments and suggestions for requested changes if any.
## Testing
A reviewer should briefly describe here how it was tested
## Code reviewing
A reviewer should briefly describe here which part was code reviewed

2024-09-27 11:40 UTC, chenejac requested changes
## General comment
This might be a nice feature to have in VIVO. 
## Testing
I found a couple of issues:
- Person filter is not working in my case. Persons are listed on left side, there are numbers in the brackets, but when I click on a person, the list of articles is not displayed (for other filter pages (Organization, Type, Year, Category,  it is working)
- Serbian alphabetical index is not working properly for two letters codes (Dž, Lj, Nj), this should list articles starting with Dž, Lj, or Nj, but it is listing at the moment articles starting with D or Ž (union of lists under D index and Ž index).
- For some languages alphabetical index is not defined properly (this can be fixed at the end of the review process)
## Code reviewing
Didn't review code yet.

2024-09-30 07:27 UTC, litvinovg commented
Thank you for testing.
> * Person filter is not working in my case. Persons are listed on left side, there are numbers in the brackets, but when I click on a person, the list of articles is not displayed (for other filter pages (Organization, Type, Year, Category,  it is working)
> 
I think Person filter is not configured to include any person related publications in default VIVO configuration https://github.com/vivo-project/VIVO/blob/04a0e75a93c99b9bd9b4e6c8ca2238617cd0ff78/home/src/main/resources/rdf/display/everytime/searchFieldsConfigurationVivo.n3#L4
I suppose it should be extended, but I think it is not linked to this PR.
> * Serbian alphabetical index is not working properly for two letters codes (Dž, Lj, Nj), this should list articles starting with Dž, Lj, or Nj, but it is listing at the moment articles starting with D or Ž (union of lists under D index and Ž index).
Thanks. There was an issue with a regular expression I used. It should be fixed now (in Vitro PR). Please try again. 
> * For some languages alphabetical index is not defined properly (this can be fixed at the end of the review process)
Sure, I think we will have to ask native speakers to check it.

2025-01-16 08:12 UTC, chenejac submitted a review, later dismissed
@litvinovg well done. If I understood well customers requested autocomplete off, therefore I think we should go with that.

2025-02-24 18:31 UTC, chenejac submitted a review, later dismissed

2025-05-15 13:24 UTC, brianjlowe approved these changes

2025-05-19 10:43 UTC, chenejac approved these changes
Thanks

2025-05-20 06:16 UTC, merged